- name: Configure hosts & deploy application
  hosts: all
  vars:
    mongo_bind_ip: 0.0.0.0
    db_host: 158.160.114.210

  handlers:
  - name: restart mongod
    become: true
    service:
      name: mongodb
      state: restarted
      daemon_reload: true
  - name: reload puma
    become: true
    systemd:
      name: puma
      state: restarted
      daemon_reload: true

  tasks:
    - name: Change mongo config file
      become: true
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongodb.conf
        mode: 0644
      tags: db-tag  # Список тэгов для задачи
      notify: restart mongod

    - name: Add unit file for Puma
      become: true
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      tags: app-tag
      notify: reload puma

    - name: Enable puma
      become: true
      systemd:
        name: puma
        enabled: yes
      tags: app-tag

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
      tags: app-tag

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith  # <-- Указываем нужную ветку
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit  # <-- В какой директории выполнить команду bundle
      tags: deploy-tag
